### ISSUE TITLE
moduł fresh-mail - zamienić jersey na Spring RestTemplate

### ISSUE THREAD

**Issue by alapierre** [SoftProject/commons#10]
To jest zadanie o bardzo niskim priorytecie. Na tą chwilę biblioteka działa bardzo dobrze. Jedyna bolączka to niepotrzebne zależności.

http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
https://github.com/alapierre/sample/tree/master/spring-rest-template

należny pamiętać o konfiguracji RestTemolate. Sugeruję skonfigurować RestTemplate wewnątrz klasy FreshMailClient - np. w konstruktorze, a nie w XML'u (będzie łatwiej używać w innych projektach).

<bean id="restTemplate" class="org.springframework.web.client.RestTemplate">
        <property name="messageConverters">
            <list>
                <bean class="org.springframework.http.converter.StringHttpMessageConverter" />
                <bean class="org.springframework.http.converter.json.MappingJacksonHttpMessageConverter"/>
            </list>
        </property>
    </bean>

**Comment by mkjasinski** [comment]
Działamy z tym?

**Comment by lbednorz** [comment]
Działać.

2015-11-16 13:32 GMT+01:00 Marcin Jasiński <notifications@github.com>:
