### ISSUE TITLE
zaimplementować subscriberAdd(List<Subscriber> list) 

### ISSUE THREAD

**Issue by alapierre** [SoftProject/commons#11]
implementacja, którą dodałem w pętli wywołuje metodę na serwerze - to mało wydajne. Jest do tego metoda w API: http://freshmail.pl/developer-api/subskrybenci-zarzadzanie-wieloma-subskrybentami-w-pojedynczym-zadaniu/

UWAGA: maksymalnie 100 rekordów jednocześnie - czyli jeśli elementów jest więcej, trzeba dzielić na paczki!

**Comment by mkjasinski** [comment]
Nie było implementacji tego mechanizmu. Kiedy z tym działać?

**Comment by lbednorz** [comment]
Jak masz moce przerobowe to walcz.

W dniu 16 listopada 2015 13:32 użytkownik Marcin Jasiński <
notifications@github.com> napisał:

**Comment by mkjasinski** [comment]
Gotowe.
